SNOW-827383 .NET Driver Unit Tests failing on non-default account's settings (#659)
Fixes of tests:
- **SFDbTransactionIT.TestTransactionRollback,
SFDbTransactionIT.TestTransactionRollbackOn2Transactions**
If account's TIMESTAMP_TYPE_MAPPING is set to TIMESTAMP_LTZ then in
testTransation TIMESTAMP is treated as TIMESTAMP_LTZ and
reader.GetDateTime throws an exception. Of course we can (a) set
session's TIMESTAMP_TYPE_MAPPING to TIMESTAMP_NTZ or (b) change
account's parameter. But as we don't test here TIMESTAMP_* variations I
think explicit creation of TIMESTAMP_NTZ is the simplest solution.
- **SFMultiStatementsIT.testWithAllQueryTypes**
On our dev envs we get: SQL compilation error: error line 1 at position
4 Invalid explain plan format 'tabular'.
Since that is not the main purpose of the test (we test here multi line
statements) I've change it to 'text'.
One more info - setting FORCE_USING_EXTERNAL_EXPLAIN = true fixes the
problem with 'tabular' on local env.